name: Recordatorio Verificación

on:
  workflow_dispatch: # Botón manual
  schedule:
    # CRONOLOGÍA (UTC):
    # Minuto: 5 (Evita la saturación de la hora en punto)
    # Hora: 14 (Son las 8 AM en CDMX)
    # Día semana: 1 (Lunes)
    - cron: '5 14 * * 1'

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests pytz

      - name: Ejecutar Aviso
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
